[package]
name = "Zoom"
homepage = "https://www.nexusmods.com/morrowind/mods/53474"
authors = [ "C3pa" ]
version = "1.2.0"

[dependencies]
assets = [ "Textures/zoom" ]

[tools.mwse]
lua-mod = "zoom"

[dependencies.mwse]
buildnumber = 3394

[dependencies.mge-xe]
version = ">=0.15.0"
